services:
  mongo:
    image: mongo
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ${DOCKERDATADIR}/komodo/db:/data/db
      - ${DOCKERDATADIR}/komodo/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}
  
  core:
    image: ghcr.io/moghtech/komodo-core:latest
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 9120:9120
    env_file: ./compose.env
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
    volumes:
      ## Store dated backups of the database - https://komo.do/docs/setup/backup
      - ${DOCKERDATADIR}/komodo/backups:/backups
      ## Store sync files on server
      # - /path/to/syncs:/syncs
      ## Optionally mount a custom core.config.toml
      # - /path/to/core.config.toml:/config/config.toml
    ## Allows for systemd Periphery connection at 
    ## "https://host.docker.internal:8120"
    # extra_hosts:
    #   - host.docker.internal:host-gateway

  ## Deploy Periphery container using this block,
  ## or deploy the Periphery binary with systemd using 
  ## https://github.com/moghtech/komodo/tree/main/scripts
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:latest
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    # user: "1000:1000"
    env_file: ./compose.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## Specify the Periphery agent root directory.
      ## Must be the same inside and outside the container,
      ## or docker will get confused. See https://github.com/moghtech/komodo/discussions/180.
      ## Default: /etc/komodo.
      - /home/shahvirb/gitsource/argon:/home/shahvirb/gitsource/argon

  komodo-import:
    image: foxxmd/komodo-import:latest
    volumes:
      ## Mount the parent directory where all subfolders are compose projects
      - /home/shahvirb/gitsource/argon:/filesOnServer
    environment:
      ## Same as host directory mounted above
      - HOST_DIR=/home/shahvirb/gitsource/argon
      ## where stacks are generated from. 'dir' or 'compose'
      - STACKS_FROM=dir
      ## Komodo Server name to use for generated Stacks
      - SERVER_NAME=argon

      ## optional
      - TZ=${TZ}
      #- IMAGE_REGISTRY_PROVIDER=
      #- IMAGE_REGISTRY_ACCOUNT=
      #- AUTO_UPDATE=false
      #- POLL_FOR_UPDATE=false
      #- KOMODO_ENV_NAME=
      #- COMPOSE_FILE_GLOB=
      #- ENV_FILE_GLOB=
    restart: no