[[stack]]
name = "stack-changedetection_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-changedetection"
files_on_host = true


[[stack]]
name = "stack-dockge_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-dockge"
git_provider = "github.com"
repo = "shahvirb/stack-dockge"
clone_path = "/home/shahvirb/gitsource/argon/stack-dockge"


[[stack]]
name = "stack-forgejo_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-forgejo"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-joplinserver_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-joplinserver"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"

[[stack]]
name = "stack-homepage_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-homepage"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-kestra_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-kestra"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-komodo_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-komodo"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


# [[stack]]
# name = "stack-komodo-stack-gen_argon"

# [stack.config]
# server = "argon"
# file_paths = [ "docker-compose.yaml" ]
# git_provider = "github.com"
# repo = "shahvirb/stack-komodo-stack-gen"
# run_directory = "docker"
# auto_pull = false

[[stack]]
name = "stack-komodo-stack-gen_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-komodo-stack-gen/docker"
files_on_host = true
auto_pull = false


[[stack]]
name = "stack-loggifly_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-loggifly"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-netalertx_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-netalertx"
files_on_host = true


[[stack]]
name = "stack-openproject_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-openproject"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-openwebui_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-openwebui"
files_on_host = true


[[stack]]
name = "stack-paperless_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-paperless"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-resticprofile_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-resticprofile"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-scrutiny_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-scrutiny"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-tandoor_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-tandoor"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-unifinetwork_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-unifinetwork"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-uptimekuma_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-uptimekuma"
files_on_host = true


[[stack]]
name = "stack-vaultwarden_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-vaultwarden"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-vikunja_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-vikunja"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-watchtower_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-watchtower"
git_provider = "github.com"
repo = "shahvirb/stack-watchtower"
clone_path = "/home/shahvirb/gitsource/argon/stack-watchtower"

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"

