[[stack]]
name = "stack-changedetection_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-changedetection"
files_on_host = true


[[stack]]
name = "stack-dockge_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-dockge"
git_provider = "github.com"
repo = "shahvirb/stack-dockge"
clone_path = "/home/shahvirb/gitsource/argon/stack-dockge"


[[stack]]
name = "stack-forgejo_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-forgejo"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-homepage_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-homepage"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-kestra"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-komodo"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-komodo-import"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
files_on_host = true


# [[stack]]
# name = "stack-komodo-stack-gen_argon"

# [stack.config]
# server = "argon"
# file_paths = [ "docker-compose.yaml" ]
# git_provider = "github.com"
# repo = "shahvirb/stack-komodo-stack-gen"
# run_directory = "docker"
# auto_pull = false

[[stack]]
name = "stack-komodo-stack-gen_argon"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/argon/stack-komodo-stack-gen/docker"
files_on_host = true
auto_pull = false


[[stack]]
name = "stack-loggifly"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-netalertx_argon"

[stack.config]
server = "argon"
run_directory = "../stack-netalertx"
file_paths = [ "docker-compose.yaml" ]
files_on_host = true


[[stack]]
name = "stack-openproject"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-openwebui"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
files_on_host = true


[[stack]]
name = "stack-resticprofile"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-tandoor"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-unifinetwork"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-uptimekuma"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
files_on_host = true


[[stack]]
name = "stack-watchtower"

[stack.config]
server = "argon"
file_paths = [ "docker-compose.yaml" ]
git_provider = "github.com"
repo = "shahvirb/stack-watchtower"

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"

