[[stack]]
name = "stack-audiobookshelf_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-audiobookshelf"
files_on_host = true


[[stack]]
name = "stack-cronicle_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-cronicle"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"

[[stack]]
name = "stack-dispatcharr_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-dispatcharr"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


# [[stack]]
# name = "stack-epicgames_mediaserver2"

# [stack.config]
# server = "mediaserver2"
# file_paths = [ "docker-compose.yaml" ]
# run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-epicgames"
# files_on_host = true


[[stack]]
name = "stack-frigate_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-frigate"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"

[[stack]]
name = "stack-glances_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-glances"
git_provider = "github.com"
repo = "shahvirb/stack-glances"
clone_path = "/home/shahvirb/gitsource/mediaserver2/stack-glances"

[[stack]]
name = "stack-immich_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-immich"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"

# [[stack]]
# name = "stack-jdownloader2_mediaserver2"

# [stack.config]
# server = "mediaserver2"
# file_paths = [ "docker-compose.yaml" ]
# run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-jdownloader2"
# files_on_host = true


[[stack]]
name = "stack-komodo-stack-gen_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-komodo-stack-gen/docker"
git_provider = "github.com"
repo = "shahvirb/stack-komodo-stack-gen"
clone_path = "/home/shahvirb/gitsource/mediaserver2/stack-komodo-stack-gen"
auto_pull = false

[[stack]]
name = "stack-plex_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-plex"
files_on_host = true

[[stack]]
name = "stack-prowlarr_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-prowlarr"
files_on_host = true

[[stack]]
name = "stack-radarr_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-radarr"
files_on_host = true

[[stack]]
name = "stack-recyclarr_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-recyclarr"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"

[[stack]]
name = "stack-resticbackup_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-resticbackup"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"


[[stack]]
name = "stack-smbcheck_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-smbcheck"
files_on_host = true
auto_pull = false


[[stack]]
name = "stack-sonarr_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-sonarr"
files_on_host = true

[[stack]]
name = "stack-tautulli_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-tautulli"
files_on_host = true


[[stack]]
name = "stack-torrent_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-torrent"
files_on_host = true

[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"