[[stack]]
name = "stack-komodo-stack-gen_mediaserver2"

[stack.config]
server = "mediaserver2"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/mediaserver2/stack-komodo-stack-gen/docker"
git_provider = "github.com"
repo = "shahvirb/stack-komodo-stack-gen"
clone_path = "/home/shahvirb/gitsource/mediaserver2/stack-komodo-stack-gen"
auto_pull = false