title: "Home Lab Dashboard"
theme: dark

navbar:
  links: []

useEqualHeights: true

layout:
  - Health:
      tab: Default
  - Devices:
      tab: Default
  - Other:
      tab: Default
  - Web:
      tab: Default
  - Media:
      tab: Media
  - Torrenting:
      tab: Media
  - Movies and TV Shows:
      tab: Media
  - System Monitoring:
      columns: 4
      style: row
      tab: Monitoring
  - Metrics & Analytics:
      tab: Monitoring
  - Infrastructure Monitoring:
      tab: Monitoring