services:
  komodo-import:
    image: foxxmd/komodo-import:latest
    restart: no
    volumes:
      ## Parent directory where all subfolders are compose projects
      - /home/shahvirb/gitsource/argon:/filesOnServer
    environment:
      ## Same as mounted directory above
      - HOST_DIR=/home/shahvirb/gitsource/argon
      ## Determines what sources to generate Stacks from
      - STACKS_FROM=dir ## Generate stacks from subfolders in directory
      ## Name of Server for this machine, in Komodo
      - SERVER_NAME=argon